//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductClient.ServiceProducts {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Urun", Namespace="http://schemas.datacontract.org/2004/07/Northwind.DTO")]
    [System.SerializableAttribute()]
    public partial class Urun : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BirimFiyatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SurumKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UrunIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BirimFiyat {
            get {
                return this.BirimFiyatField;
            }
            set {
                if ((this.BirimFiyatField.Equals(value) != true)) {
                    this.BirimFiyatField = value;
                    this.RaisePropertyChanged("BirimFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SurumKodu {
            get {
                return this.SurumKoduField;
            }
            set {
                if ((this.SurumKoduField.Equals(value) != true)) {
                    this.SurumKoduField = value;
                    this.RaisePropertyChanged("SurumKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrunAd {
            get {
                return this.UrunAdField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdField, value) != true)) {
                    this.UrunAdField = value;
                    this.RaisePropertyChanged("UrunAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UrunID {
            get {
                return this.UrunIDField;
            }
            set {
                if ((this.UrunIDField.Equals(value) != true)) {
                    this.UrunIDField = value;
                    this.RaisePropertyChanged("UrunID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProducts.IServiceProducts")]
    public interface IServiceProducts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/GetProducts", ReplyAction="http://tempuri.org/IServiceProducts/GetProductsResponse")]
        ProductClient.ServiceProducts.Urun[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/GetProducts", ReplyAction="http://tempuri.org/IServiceProducts/GetProductsResponse")]
        System.Threading.Tasks.Task<ProductClient.ServiceProducts.Urun[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/GetOneProduct", ReplyAction="http://tempuri.org/IServiceProducts/GetOneProductResponse")]
        ProductClient.ServiceProducts.Urun GetOneProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/GetOneProduct", ReplyAction="http://tempuri.org/IServiceProducts/GetOneProductResponse")]
        System.Threading.Tasks.Task<ProductClient.ServiceProducts.Urun> GetOneProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/UpdatePrice", ReplyAction="http://tempuri.org/IServiceProducts/UpdatePriceResponse")]
        void UpdatePrice(int id, decimal fiyat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/UpdatePrice", ReplyAction="http://tempuri.org/IServiceProducts/UpdatePriceResponse")]
        System.Threading.Tasks.Task UpdatePriceAsync(int id, decimal fiyat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/DeleteProduct", ReplyAction="http://tempuri.org/IServiceProducts/DeleteProductResponse")]
        void DeleteProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducts/DeleteProduct", ReplyAction="http://tempuri.org/IServiceProducts/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProductsChannel : ProductClient.ServiceProducts.IServiceProducts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductsClient : System.ServiceModel.ClientBase<ProductClient.ServiceProducts.IServiceProducts>, ProductClient.ServiceProducts.IServiceProducts {
        
        public ServiceProductsClient() {
        }
        
        public ServiceProductsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProductClient.ServiceProducts.Urun[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<ProductClient.ServiceProducts.Urun[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public ProductClient.ServiceProducts.Urun GetOneProduct(int id) {
            return base.Channel.GetOneProduct(id);
        }
        
        public System.Threading.Tasks.Task<ProductClient.ServiceProducts.Urun> GetOneProductAsync(int id) {
            return base.Channel.GetOneProductAsync(id);
        }
        
        public void UpdatePrice(int id, decimal fiyat) {
            base.Channel.UpdatePrice(id, fiyat);
        }
        
        public System.Threading.Tasks.Task UpdatePriceAsync(int id, decimal fiyat) {
            return base.Channel.UpdatePriceAsync(id, fiyat);
        }
        
        public void DeleteProduct(int id) {
            base.Channel.DeleteProduct(id);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(int id) {
            return base.Channel.DeleteProductAsync(id);
        }
    }
}
